matrix:
  include:
    - language: android
      jdk: oraclejdk8

      licenses:
        - android-sdk-license-.+
        - '.+'

      android:
        components:
          - tools
          - platform-tools
          - build-tools-25.0.2

          - android-22

          - extra-google-google_play_services
          - extra-google-m2repository
          - extra-android-m2repository
          - addon-google_apis-google-19

          - sys-img-armeabi-v7a-android-22
          - sys-img-armeabi-v7a-android-17

      branches:
        only:
          - master
          - develop

    - language: node_js
      node_js:
        - "stable"

      before_install:
        - cd ./api

  after_success:
    - cd ./api
    - npm run coveralls

  deploy:
    provider: heroku
    api_key:
      secure: "7eec7a0d-9b76-44b1-b861-90610f33260c"
    app: programmeren-tent-4
    on:
      - all_branches
