matrix:
  include:
    - language: android
      jdk: oraclejdk8
      cache: false
      dist: trusty
      sudo: required
      group: edge

      before_install:
        - mkdir "$ANDROID_HOME/licenses" || true
        - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
        - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
        - source /opt/jdk_switcher/jdk_switcher.sh
        - jdk_switcher use default

      licenses:
        - android-sdk-license-.+
        - '.+'


      licenses:
        - android-sdk-license-.+
        - '.+'

      android:
        components:
          - tools
          - platform-tools
          - build-tools-25.0.2

          - android-22

          - extra-google-google_play_services
          - extra-google-m2repository
          - extra-android-m2repository
          - addon-google_apis-google-19

          - sys-img-armeabi-v7a-android-22
          - sys-img-armeabi-v7a-android-17

      branches:
        only:
          - master
          - develop

    - language: node_js
      node_js:
        - "stable"

      before_install:
        - cd ./api

  after_success:
    - cd ./api
    - npm run coveralls

  deploy:
    provider: heroku
    api_key:
      secure: "7eec7a0d-9b76-44b1-b861-90610f33260c"
    app: programmeren-tent-4
    on:
      - all_branches
